const DRIVER_MANAGEMENT = "/panel/dashboard/DriverManagement";
const PASSENGER_MANAGEMENT = "/panel/dashboard/PassengerManagement";
const HALFWAY_MANAGEMENT = "/panel/dashboard/HalfwayManagement";
const REPORT_MANAGEMENT = "/panel/dashboard/ReportManagement";
const FINANCE_MANAGEMENT = "/panel/dashboard/FinanceManagement";
const DASHBOARD = "/panel/dashboard";
const PROFILE = "/panel/dashboard/Profile";
const TICKETBOOKING = "/panel/dashboard/TicketBooking/BookTicket";
const TICKETHISTORY = "/panel/dahsboard/TicketHistory";
export { DRIVER_MANAGEMENT,PASSENGER_MANAGEMENT,HALFWAY_MANAGEMENT,REPORT_MANAGEMENT,FINANCE_MANAGEMENT,DASHBOARD ,PROFILE,TICKETHISTORY,TICKETBOOKING}